"""reading_quality

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-21 22:03:35.348759

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality', sa.String(length=16), server_default='good', nullable=False))
        batch_op.add_column(sa.Column('src_ts', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('readings_hourly', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pct_good', sa.Float(), server_default='1', nullable=False))
        batch_op.add_column(sa.Column('n_bad', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_quality', sa.String(length=16), server_default='good', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('last_quality')

    with op.batch_alter_table('readings_hourly', schema=None) as batch_op:
        batch_op.drop_column('n_bad')
        batch_op.drop_column('pct_good')

    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_column('src_ts')
        batch_op.drop_column('quality')

    # ### end Alembic commands ###
