"""sensor_raw_range

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-21 22:14:05.517386

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_raw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_raw', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('max_raw')
        batch_op.drop_column('min_raw')

    # ### end Alembic commands ###
