"""indexes

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-21 22:33:49.982652

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0005'
down_revision = '0004'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.create_index('ix_alarm_events_sensor_open', ['sensor_id', 'ended_at'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('uq_commands_sensor_open', ['sensor_id'], unique=True, sqlite_where=sa.text("status IN ('pending', 'sent')"), postgresql_where=sa.text("status IN ('pending', 'sent')"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index('uq_commands_sensor_open', sqlite_where=sa.text("status IN ('pending', 'sent')"), postgresql_where=sa.text("status IN ('pending', 'sent')"))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_user_id'))

    with op.batch_alter_table('alarm_events', schema=None) as batch_op:
        batch_op.drop_index('ix_alarm_events_sensor_open')

    # ### end Alembic commands ###
