"""command_safety

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-21 23:32:42.021624

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # CommandStatus ga 'expired' qiymati: Postgres da enum turi kengaytiriladi (SQLite — VARCHAR)
    if op.get_bind().dialect.name == "postgresql":
        op.execute("ALTER TYPE commandstatus ADD VALUE IF NOT EXISTS 'expired'")
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_setpoint', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_setpoint', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_rate_per_min', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('requires_dual_approval', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('command_ttl_s', sa.Integer(), server_default='300', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_column('command_ttl_s')
        batch_op.drop_column('requires_dual_approval')
        batch_op.drop_column('max_rate_per_min')
        batch_op.drop_column('max_setpoint')
        batch_op.drop_column('min_setpoint')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('sent_at')
        batch_op.drop_column('expires_at')

    # ### end Alembic commands ###
