"""gateway_keys

Revision ID: 0008
Revises: 0007
Create Date: 2026-09-22 00:00:19.433511

"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = '0008'
down_revision = '0007'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingest_key_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('ingest_key_last_used_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('command_key', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('command_key_expires_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('command_key_last_used_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('command_key_last_used_at')
        batch_op.drop_column('command_key_expires_at')
        batch_op.drop_column('command_key')
        batch_op.drop_column('ingest_key_last_used_at')
        batch_op.drop_column('ingest_key_expires_at')

    # ### end Alembic commands ###
